apiVersion: v1
kind: LimitRange
metadata:
  name: memory-cpu-limit-range
  namespace: dev-ns
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 1
    defaultRequest:
      memory: 250Mi
      cpu: 0.4
    type: Container
